server:
  port: 80

spring:
  application:
    name: Movie-Ticket

  datasource:
    url: jdbc:mysql://localhost:3306/book-my-ticket?createDatabaseIfNotExist=true
    username: root
    password: yashu

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      url: redis://localhost:6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: yashavanthakumarrt53@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

admin:
  email: yashu@gmail.com
  password: Yashu

cloudinary:
  url: ${CLOUDINARY_URL}